// src/pages/repositories/Repositories.jsx
import React, { useEffect, useState } from "react";
import Footer from "../../core/Footer/Footer";
import Loader from "../../core/loader/Loader";
import "./Repositories.scss";
import {
  RiGitBranchLine,
  RiGitRepositoryFill,
  RiUserFollowLine,
} from "react-icons/ri";
import { FaStar } from "react-icons/fa";
import bg from "../../assets/sprinkle.svg";

const Repositories = () => {
  const [isFetching, setIsFetching] = useState(true);
  const [repos, setRepos] = useState([]);
  const [user, setUser] = useState(null);
  const langs = {
    "c#": "#af36ff",
    scss: "#ff36c6",
    html: "#ff5917",
    javascript: "#ffdf6b",
    typescript: "#0096ed",
    css: "#00fbff",
    null: "#ff00a2",
  };

  useEffect(() => {
    (async () => {
      var data = await fetch("https://api.github.com/users/bforbiggy/repos").then(
        (response) => response.json()
      );

      var user = await fetch("https://api.github.com/users/bforbiggy").then(
        (response) => response.json()
      );

      setRepos(
        data
          .filter((item) => {
            return item.fork == false;
          })
          .sort((a, b) => {
            return b.stargazers_count - a.stargazers_count;
          })
      );

      setUser(user);

      setIsFetching(false);
    })();
  }, []);

  const getLanguageColor = (language) => {
    language = language ?? "null";
    return langs[language?.toLowerCase()] ?? "#FFF";
  };

  return (
    <div
      className="repositories-container"
      style={{ backgroundImage: `url(${bg}` }}
    >
      <main>
        {isFetching ? (
          <Loader local={true} />
        ) : (
          <>
            <div className="user">
              {user ? (
                <>
                  <div className="avatar">
                    <img src="https://github.com/bforbiggy.png" alt="Biggy's pfp" />
                  </div>
                  <div className="user-info">
                    <div className="name">🍧 {user.login} 🍧</div>
                    <div className="bio">{user.bio}</div>
                    <div className="field">
                      <div className="key">
                        <RiGitRepositoryFill />
                        Repositories:~ ${" "}
                      </div>
                      <div className="value">{user.public_repos}</div>
                    </div>
                    <div className="field">
                      <div className="key">
                        <RiUserFollowLine />
                        Followers:~ ${" "}
                      </div>
                      <div className="value">{user.followers}</div>
                    </div>
                  </div>
                </>
              ) : (
                <></>
              )}
            </div>
            <div className="repositories">
              <div className="title">bforbiggy@Repositories:~ $</div>
              {repos.length > 0 ? (
                repos?.map((data) => (
                  <a
                    href={data.html_url}
                    target="_blank"
                    className="repository-container"
                  >
                    <div className="name">
                      <RiGitBranchLine /> {data.name}
                    </div>
                    <div className="description">{data.description}</div>
                    <div className="info-container">
                      <div className="item">
                        <div className="key">Main Language</div>
                        <div
                          className="value"
                          style={{
                            color: getLanguageColor(data.language),
                            fontSize: "1.1em",
                          }}
                        >
                          {data.language ?? "null"}
                        </div>
                      </div>
                      <div className="item">
                        <div className="key">Created Date</div>
                        <div className="value">
                          {new Date(data.created_at).toLocaleDateString()}
                        </div>
                      </div>
                      <div className="item">
                        <div className="key">
                          <FaStar />
                        </div>
                        <div className="value">{data.stargazers_count}</div>
                      </div>
                    </div>
                  </a>
                ))
              ) : (
                <></>
              )}
            </div>
          </>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default Repositories;

// src/routes/repositories/+page.svelte
<script>
	import { onMount, onDestroy, getContext } from "svelte";

	let repos = null;
	let user = null;

	onMount(async () => {
		console.log("WTF");
		let response, data;

		response = await fetch("https://api.github.com/users/bforbiggy/repos");
		data = await response.json();
		repos = data
			.filter((item) => !item.fork)
			.sort(
				(a, b) => b.stargazers_count - a.stargazers_count || b.size - a.size
			);

		response = await fetch("https://api.github.com/users/bforbiggy");
		data = await response.json();
		user = data;
	});

	const menu = getContext("menu");
	onMount(() => {
		$menu.icons = true;
	});
	onDestroy(() => {
		$menu.icons = false;
	});
</script>

<div
	class="min-h-[100vh] min-w-[100vw] max-w-[100vw] bg-slate-950
			flex justify-center gap-32 p-28"
>
	<div
		class="z-10 fixed inset-0 m-auto w-full h-full bg-[url('$lib/assets/Sprinkle.svg')] opacity-30"
	/>

	{#if !user}
		<p class="z-20 text-middle text-4xl text-amber-50">Loading....</p>
	{:else}
		<div
			class="z-20 w-min h-min bg-slate-900 rounded-md border-2 border-slate-800
				p-3 flex flex-col gap-2 text-center text-amber-50"
		>
			<img
				class="min-w-64 max-w-64 h-auto rounded-full
					border-4 border-teal-800"
				src={user.avatar_url}
				alt=""
			/>
			<div class="flex justify-between text-3xl py-1">
				<span>🎴</span>
				<p>{user.login}</p>
				<span>🎴</span>
			</div>
			<p>{user.bio}</p>
			<div class="w-full flex justify-between text-md">
				<p>
					<span class="icon-[carbon--cics-program] text-red-500" />
					Repositories:
				</p>
				<p class="text-red-500">{user.public_repos}</p>
			</div>
			<div class="w-full flex justify-between text-md">
				<p>
					<span class="icon-[carbon--user-profile] text-red-500" />
					Followers:
				</p>
				<p class="text-red-500">{user.followers}</p>
			</div>
		</div>

		<div class="z-20 flex flex-col gap-6 text-center">
			{#each repos as repo}
				<a
					class="max-w-[500px] flex flex-col gap-3 rounded-xl
						border-2 border-neutral-800 p-4 bg-slate-950
						hover:scale-110 hover:border-rose-400 transition-all
						text-wrap text-emerald-50"
					href={repo.html_url}
					target="_blank"
				>
					<div class="text-left text-2xl text-white">
						<span class="icon-[carbon--branch] text-green-500" />
						{repo.name}
					</div>

					<div class="min-h-20 text-left">
						{repo.description ?? "No description!"}
					</div>
					<div class="flex justify-around">
						<div class="flex flex-col">
							<div>Main Language</div>
							<div>
								{repo.language ?? "Unknown"}
							</div>
						</div>

						<div class="flex flex-col">
							<div>Created On</div>
							<div>
								{new Date(repo.created_at).toLocaleDateString()}
							</div>
						</div>

						<div class="flex flex-col">
							<span class="icon-[carbon--star-filled]" />
							<div>{repo.stargazers_count}</div>
						</div>
					</div>
				</a>
			{/each}
		</div>
	{/if}
</div>
